package dbproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Evaluator_show_update_job extends javax.swing.JFrame {
    
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    public Evaluator_show_update_job() {
        conn=CheckConnection.ConnectDb();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_table = new javax.swing.JTable();
        back_button = new javax.swing.JButton();
        show_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        start_date = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        edra = new javax.swing.JLabel();
        Salary = new javax.swing.JTextField();
        Position = new javax.swing.JTextField();
        Edra = new javax.swing.JTextField();
        submission_date = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        evaluator = new javax.swing.JLabel();
        afm = new javax.swing.JLabel();
        Submission_date = new javax.swing.JTextField();
        Title = new javax.swing.JTextField();
        Evaluator = new javax.swing.JTextField();
        AFM = new javax.swing.JTextField();
        Start_date = new javax.swing.JTextField();
        job_id = new javax.swing.JLabel();
        Job_id = new javax.swing.JTextField();
        evaluator_username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Show and update your jobs");

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setText("Evaluator Username");

        show_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        show_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Id", "Satart Date", "Salary", "Position", "Edra", "Announce Date", "Submission Date", "Title", "Evaluator", "AFM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(show_table);

        back_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        show_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        show_button.setText("Show");
        show_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_buttonActionPerformed(evt);
            }
        });

        update_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        start_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        start_date.setText("Start Date");

        salary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salary.setText("Salary");

        position.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        position.setText("Position");

        edra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edra.setText("Edra");

        Salary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Position.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Edra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        submission_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submission_date.setText("Submission Date");

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setText("Title");

        evaluator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        evaluator.setText("Evaluator");

        afm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        afm.setText("AFM");

        Submission_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Evaluator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        AFM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Start_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        job_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        job_id.setText("Job Id");

        Job_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        evaluator_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(username)
                .addGap(101, 101, 101)
                .addComponent(evaluator_username, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(show_button)
                .addGap(299, 299, 299)
                .addComponent(update_button)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(start_date)
                            .addComponent(salary)
                            .addComponent(position)
                            .addComponent(edra))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Salary, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(Position)
                            .addComponent(Edra)
                            .addComponent(Start_date))
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(afm)
                                    .addComponent(evaluator)
                                    .addComponent(title))
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Title)
                                    .addComponent(Evaluator)
                                    .addComponent(AFM)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submission_date)
                                .addGap(72, 72, 72)
                                .addComponent(Submission_date, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(job_id)
                        .addGap(81, 81, 81)
                        .addComponent(Job_id, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(evaluator_username, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_date)
                    .addComponent(submission_date)
                    .addComponent(Submission_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Start_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salary)
                    .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(position)
                    .addComponent(evaluator)
                    .addComponent(Evaluator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edra)
                    .addComponent(Edra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afm)
                    .addComponent(AFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(job_id)
                    .addComponent(Job_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(show_button)
                    .addComponent(update_button)
                    .addComponent(back_button))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_buttonActionPerformed
        // TODO add your handling code here:
        String evalusername=evaluator_username.getText();
     
        try{
            String sql_query="SELECT * FROM job WHERE evaluator=?";
            pst=conn.prepareStatement(sql_query);
            
            pst.setString(1, evalusername);
            
            rs=pst.executeQuery();
            show_table.setModel(DbUtils.resultSetToTableModel(rs));
       
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
             }
    }//GEN-LAST:event_show_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        Evaluator_Main_Frame EMF = new Evaluator_Main_Frame();
        Evaluator_Main_Frame.eval_username.setText(evaluator_username.getText());
        EMF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        String startdate=Start_date.getText();
        String salary=Salary.getText();
        String position=Position.getText();
        String edra=Edra.getText();
        String submissiondate=Submission_date.getText();
        String title=Title.getText();
        String evaluator=Evaluator.getText();
        String afm=AFM.getText();
        String jobid=Job_id.getText();
     
        try{
            String str0 = "SET @user=?";
            pst=conn.prepareStatement(str0);
            pst.setString(1, evaluator_username.getText());
            rs = pst.executeQuery();
            //==================================================
            String sql_query="UPDATE job SET start_date = ?, salary = ?, position = ?,edra = ?, "
            + "submission_date = ?, Title = ?, evaluator = ?, AFM = ? WHERE id = ?";
            pst=conn.prepareStatement(sql_query);
            
            pst.setString(1, startdate);
            pst.setString(2, salary);
            pst.setString(3, position);
            pst.setString(4, edra);
            pst.setString(5, submissiondate);
            pst.setString(6, title);
            pst.setString(7, evaluator);
            pst.setString(8, afm);
            pst.setString(9, jobid);
            
            rs=pst.executeQuery();
            
            JOptionPane.showMessageDialog(null, "Data succesfully updated!");
            
            Evaluator_Main_Frame EMF = new Evaluator_Main_Frame();
            Evaluator_Main_Frame.eval_username.setText(evaluator_username.getText());
            EMF.setVisible(true);
            this.dispose();
            
             }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
             }
    }//GEN-LAST:event_update_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluator_show_update_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluator_show_update_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluator_show_update_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluator_show_update_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluator_show_update_job().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AFM;
    private javax.swing.JTextField Edra;
    private javax.swing.JTextField Evaluator;
    private javax.swing.JTextField Job_id;
    private javax.swing.JTextField Position;
    private javax.swing.JTextField Salary;
    private javax.swing.JTextField Start_date;
    private javax.swing.JTextField Submission_date;
    private javax.swing.JTextField Title;
    private javax.swing.JLabel afm;
    private javax.swing.JButton back_button;
    private javax.swing.JLabel edra;
    private javax.swing.JLabel evaluator;
    public static javax.swing.JLabel evaluator_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel job_id;
    private javax.swing.JLabel position;
    private javax.swing.JLabel salary;
    private javax.swing.JButton show_button;
    private javax.swing.JTable show_table;
    private javax.swing.JLabel start_date;
    private javax.swing.JLabel submission_date;
    private javax.swing.JLabel title;
    private javax.swing.JButton update_button;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
