package dbproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Evaluator_change_data_account extends javax.swing.JFrame {
    
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    public Evaluator_change_data_account() {
        conn=CheckConnection.ConnectDb();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        eval_current_username = new javax.swing.JLabel();
        eval_username = new javax.swing.JLabel();
        eval_name = new javax.swing.JLabel();
        eval_surname = new javax.swing.JLabel();
        eval_exp_years = new javax.swing.JLabel();
        eval_code = new javax.swing.JLabel();
        Eval_username = new javax.swing.JTextField();
        Eval_name = new javax.swing.JTextField();
        Eval_surname = new javax.swing.JTextField();
        Eval_exp_years = new javax.swing.JTextField();
        Eval_code = new javax.swing.JTextField();
        eval_firm = new javax.swing.JLabel();
        eval_mo = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        change_button = new javax.swing.JButton();
        Eval_firm = new javax.swing.JTextField();
        Eval_mo = new javax.swing.JTextField();
        show_button = new javax.swing.JButton();
        Eval_current_username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Change the data of your account");

        eval_current_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eval_current_username.setText("Current username");

        eval_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eval_username.setText("username");

        eval_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eval_name.setText("name");

        eval_surname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eval_surname.setText("surname");

        eval_exp_years.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eval_exp_years.setText("exp_years");

        eval_code.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eval_code.setText("code");

        Eval_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Eval_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Eval_surname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Eval_exp_years.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Eval_code.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        eval_firm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eval_firm.setText("firm");

        eval_mo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eval_mo.setText("MO");

        back_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        change_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        change_button.setText("Change");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        Eval_firm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Eval_mo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        show_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        show_button.setText("Show");
        show_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_buttonActionPerformed(evt);
            }
        });

        Eval_current_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eval_current_username)
                            .addComponent(eval_username)
                            .addComponent(eval_name)
                            .addComponent(eval_surname)
                            .addComponent(eval_exp_years)
                            .addComponent(eval_code)
                            .addComponent(eval_firm)
                            .addComponent(eval_mo))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Eval_surname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(Eval_exp_years, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Eval_code, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Eval_firm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Eval_mo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Eval_username)
                            .addComponent(Eval_name)
                            .addComponent(Eval_current_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)))
                .addGap(75, 108, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(show_button)
                .addGap(96, 96, 96)
                .addComponent(change_button)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eval_current_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eval_current_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eval_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eval_username))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eval_name)
                    .addComponent(Eval_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eval_surname)
                    .addComponent(Eval_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eval_exp_years)
                    .addComponent(Eval_exp_years, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eval_code)
                    .addComponent(Eval_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eval_firm)
                    .addComponent(Eval_firm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eval_mo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eval_mo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(change_button)
                    .addComponent(back_button)
                    .addComponent(show_button))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        Evaluator_Main_Frame EMF = new Evaluator_Main_Frame();
        Evaluator_Main_Frame.eval_username.setText(Eval_current_username.getText());
        EMF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        // TODO add your handling code here:
        String curruser=Eval_current_username.getText();
        String username=Eval_username.getText();
        String name=Eval_name.getText();
        String surname=Eval_surname.getText();
        String exp_years=Eval_exp_years.getText();
        String code=Eval_code.getText();
        String firm=Eval_firm.getText();
        String mo=Eval_mo.getText();
        
        try{
            String sql_query="UPDATE evaluator SET username =?, name = ?, surname = ?, exp_years = ?, code = ?, firm = ?, MO = ? WHERE username = ?";
            pst=conn.prepareStatement(sql_query);
            
            pst.setString(1, username);
            pst.setString(2, name);
            pst.setString(3, surname);
            pst.setString(4, exp_years);
            pst.setString(5, code);
            pst.setString(6, firm);
            pst.setString(7, mo);
            pst.setString(8, curruser);
            
            rs=pst.executeQuery();
            
            JOptionPane.showMessageDialog(null, "Data succesfully changed!");
            
            Evaluator_Main_Frame EMF = new Evaluator_Main_Frame();
            Evaluator_Main_Frame.eval_username.setText(Eval_current_username.getText());
            EMF.setVisible(true);
            this.dispose();
            
             }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
             }
    }//GEN-LAST:event_change_buttonActionPerformed

    private void show_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_buttonActionPerformed
        // TODO add your handling code here:
        String evaluser=Eval_current_username.getText();
     
        try{
            String sql_query="SELECT * FROM evaluator WHERE username=?";
            pst=conn.prepareStatement(sql_query);
            
            pst.setString(1, evaluser);
            
            rs=pst.executeQuery();
            while(rs.next()){
                Eval_username.setText(rs.getString("username"));
                Eval_name.setText(rs.getString("name"));
                Eval_surname.setText(rs.getString("surname"));
                Eval_exp_years.setText(rs.getString("exp_years"));
                Eval_code.setText(rs.getString("code"));
                Eval_firm.setText(rs.getString("firm"));
                Eval_mo.setText(rs.getString("MO"));
            }
       
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
             }
    }//GEN-LAST:event_show_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluator_change_data_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluator_change_data_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluator_change_data_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluator_change_data_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluator_change_data_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Eval_code;
    public static javax.swing.JLabel Eval_current_username;
    private javax.swing.JTextField Eval_exp_years;
    private javax.swing.JTextField Eval_firm;
    private javax.swing.JTextField Eval_mo;
    private javax.swing.JTextField Eval_name;
    private javax.swing.JTextField Eval_surname;
    private javax.swing.JTextField Eval_username;
    private javax.swing.JButton back_button;
    private javax.swing.JButton change_button;
    private javax.swing.JLabel eval_code;
    private javax.swing.JLabel eval_current_username;
    private javax.swing.JLabel eval_exp_years;
    private javax.swing.JLabel eval_firm;
    private javax.swing.JLabel eval_mo;
    private javax.swing.JLabel eval_name;
    private javax.swing.JLabel eval_surname;
    private javax.swing.JLabel eval_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton show_button;
    // End of variables declaration//GEN-END:variables
}
