package dbproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Evaluator_insert_job extends javax.swing.JFrame {
    
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    public Evaluator_insert_job() {
        conn=CheckConnection.ConnectDb();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        job_id = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        job_title = new javax.swing.JLabel();
        afm = new javax.swing.JLabel();
        antikeim_title = new javax.swing.JLabel();
        belongs_to = new javax.swing.JLabel();
        start_date = new javax.swing.JLabel();
        edra = new javax.swing.JLabel();
        announce_date = new javax.swing.JLabel();
        submission_date = new javax.swing.JLabel();
        evaluator = new javax.swing.JLabel();
        antikeim_descr = new javax.swing.JLabel();
        Job_id = new javax.swing.JTextField();
        Salary = new javax.swing.JTextField();
        Position = new javax.swing.JTextField();
        Title = new javax.swing.JTextField();
        AFM = new javax.swing.JTextField();
        Belongs_to = new javax.swing.JTextField();
        Start_date = new javax.swing.JTextField();
        Edra = new javax.swing.JTextField();
        Submission_date = new javax.swing.JTextField();
        Antikeim_descr = new javax.swing.JTextField();
        insert_job_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        Announce_date = new javax.swing.JTextField();
        Antikeim_Title = new javax.swing.JTextField();
        Evaluator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Insert data for the new job");

        job_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        job_id.setText("Job Id");

        salary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salary.setText("Salary");

        position.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        position.setText("Position");

        job_title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        job_title.setText("Title");

        afm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        afm.setText("AFM");

        antikeim_title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        antikeim_title.setText("Antikeim Title");

        belongs_to.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        belongs_to.setText("Belongs To");

        start_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        start_date.setText("Start Date");

        edra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edra.setText("Edra");

        announce_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        announce_date.setText("Announce Date");

        submission_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submission_date.setText("Submission Date");

        evaluator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        evaluator.setText("Evaluator");

        antikeim_descr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        antikeim_descr.setText("Antikeim Description");

        Job_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Salary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Position.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        AFM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Belongs_to.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Start_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Edra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Submission_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Antikeim_descr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        insert_job_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        insert_job_button.setText("Insert Job");
        insert_job_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_job_buttonActionPerformed(evt);
            }
        });

        back_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        Announce_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Antikeim_Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Evaluator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(job_id)
                                    .addComponent(belongs_to))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Job_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(Salary, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Position, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Belongs_to)))
                            .addComponent(position)
                            .addComponent(salary)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(antikeim_title)
                                    .addComponent(afm)
                                    .addComponent(job_title))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(AFM, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Title, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Antikeim_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(announce_date, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submission_date, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(evaluator, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(antikeim_descr))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Edra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Start_date, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Submission_date, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Antikeim_descr)
                            .addComponent(Announce_date, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(Evaluator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(insert_job_button))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(job_id)
                    .addComponent(start_date)
                    .addComponent(Job_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Start_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salary)
                    .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edra))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(position)
                    .addComponent(announce_date)
                    .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Announce_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(job_title)
                    .addComponent(submission_date)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submission_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afm)
                            .addComponent(evaluator)
                            .addComponent(AFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(antikeim_title)
                            .addComponent(antikeim_descr)
                            .addComponent(Antikeim_descr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Antikeim_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(belongs_to)
                            .addComponent(Belongs_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_job_button)
                            .addComponent(back_button))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Evaluator, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        Evaluator_Main_Frame EMF = new Evaluator_Main_Frame();
        Evaluator_Main_Frame.eval_username.setText(Evaluator.getText());
        EMF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void insert_job_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_job_buttonActionPerformed
        // TODO add your handling code here:
        String jobid=Job_id.getText();
        String salary=Salary.getText();
        String position=Position.getText();
        String title=Title.getText();
        String afm=AFM.getText();
        String startdate=Start_date.getText();
        String edra=Edra.getText();
        String announcedate=Announce_date.getText();
        String submissiondate=Submission_date.getText();
        String evaluator=Evaluator.getText();
        String antikeimtitle=Antikeim_Title.getText();
        String antikeimdescr=Antikeim_descr.getText();
        String belongsto=Belongs_to.getText();
        
        try{
            String str0 = "SET @user=?";
            pst=conn.prepareStatement(str0);
            pst.setString(1, Evaluator.getText());
            rs = pst.executeQuery();
            //==============================================
            String str="INSERT INTO job(id, start_date, salary, position, edra, announce_date, submission_date, Title, evaluator, AFM) VALUES\n" +
            "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst=conn.prepareStatement(str);
            
            pst.setString(1, jobid);
            pst.setString(2, startdate);
            pst.setString(3, salary);
            pst.setString(4, position);
            pst.setString(5, edra);
            pst.setString(6, announcedate);
            pst.setString(7, submissiondate);
            pst.setString(8, title);
            pst.setString(9, evaluator);
            pst.setString(10, afm);
            
            rs=pst.executeQuery();
            
            /*************************************************/
            
            String str1="INSERT INTO antikeim (title, descr, belongs_to) VALUES (?, ?, ?)";
            pst=conn.prepareStatement(str1);
            
            pst.setString(1, antikeimtitle);
            pst.setString(2, antikeimdescr);
            pst.setString(3, belongsto);
            
            rs=pst.executeQuery();
            /************************************************/
        
            String str2="INSERT INTO NEEDS (job_id, antikeim_title) VALUES (?, ?)";
            pst=conn.prepareStatement(str2);
            
            pst.setString(1, jobid);
            pst.setString(2, antikeimtitle);
            
            rs=pst.executeQuery();
            
            JOptionPane.showMessageDialog(null, "Job inserted succesfully!");
            
            Evaluator_Main_Frame EMF = new Evaluator_Main_Frame();
            Evaluator_Main_Frame.eval_username.setText(Evaluator.getText());
            EMF.setVisible(true);
            this.dispose();
            
             }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
             }
    }//GEN-LAST:event_insert_job_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluator_insert_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluator_insert_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluator_insert_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluator_insert_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluator_insert_job().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AFM;
    private javax.swing.JTextField Announce_date;
    private javax.swing.JTextField Antikeim_Title;
    private javax.swing.JTextField Antikeim_descr;
    private javax.swing.JTextField Belongs_to;
    private javax.swing.JTextField Edra;
    public static javax.swing.JLabel Evaluator;
    private javax.swing.JTextField Job_id;
    private javax.swing.JTextField Position;
    private javax.swing.JTextField Salary;
    private javax.swing.JTextField Start_date;
    private javax.swing.JTextField Submission_date;
    private javax.swing.JTextField Title;
    private javax.swing.JLabel afm;
    private javax.swing.JLabel announce_date;
    private javax.swing.JLabel antikeim_descr;
    private javax.swing.JLabel antikeim_title;
    private javax.swing.JButton back_button;
    private javax.swing.JLabel belongs_to;
    private javax.swing.JLabel edra;
    private javax.swing.JLabel evaluator;
    private javax.swing.JButton insert_job_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel job_id;
    private javax.swing.JLabel job_title;
    private javax.swing.JLabel position;
    private javax.swing.JLabel salary;
    private javax.swing.JLabel start_date;
    private javax.swing.JLabel submission_date;
    // End of variables declaration//GEN-END:variables
}
