package dbproject;

import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class Evaluator_Grades extends javax.swing.JFrame {

    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Evaluator_Grades() {
        conn=CheckConnection.ConnectDb();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        eval_username_5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_count = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_job = new javax.swing.JTable();
        eval_update_grade_BTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        job_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        grade1_comments = new javax.swing.JTextField();
        grade1 = new javax.swing.JTextField();
        grade2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        grade3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        grade_affected = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        empl_username = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Page");

        eval_username_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eval_username_5.setForeground(new java.awt.Color(0, 102, 102));
        eval_username_5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        table_count.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "job ID", "count"
            }
        ));
        jScrollPane1.setViewportView(table_count);
        if (table_count.getColumnModel().getColumnCount() > 0) {
            table_count.getColumnModel().getColumn(0).setHeaderValue("job ID");
            table_count.getColumnModel().getColumn(1).setHeaderValue("count");
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Αριθμός αιτήσεων ανα θέση");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Θέσεις που εχει παρέλθει η ημερομηνία υποβολής");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        table_job.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(table_job);

        eval_update_grade_BTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eval_update_grade_BTN.setForeground(new java.awt.Color(0, 102, 102));
        eval_update_grade_BTN.setText("Ενημέρωση Βαθμολογιών");
        eval_update_grade_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eval_update_grade_BTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("για την θεση με id=");

        job_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Βαθμός Συνέντευξης");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Σχόλια Συνέντευξης");

        grade1_comments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        grade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        grade2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Βαθμός report");

        grade3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Βαθμός πτυχίων, ....");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("και τον υπάλληλο με username:");

        empl_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(194, 194, 194))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grade1_comments, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181)
                                .addComponent(grade_affected, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grade1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(grade2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(grade3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(422, 422, 422)
                                .addComponent(eval_username_5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(eval_update_grade_BTN)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(job_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(empl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eval_username_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eval_update_grade_BTN)
                    .addComponent(jLabel2)
                    .addComponent(job_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(empl_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(grade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(grade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(grade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(grade1_comments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grade_affected, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String str = "SELECT job_id, COUNT(RE.job_id) \n" +
                         "FROM requestsevaluation AS RE\n" +
                         "INNER JOIN job AS J ON RE.job_id=J.id\n" +
                         "INNER JOIN Evaluation AS E ON J.id=E.jobid\n" +
                         "WHERE RE.empl_usrname=E.empl_username AND job_id IN\n" +
                         "(SELECT id FROM job where evaluator=?)\n" +
                         "GROUP BY RE.job_id;";
            pst=conn.prepareStatement(str);
            pst.setString(1, eval_username_5.getText());
            
            rs = pst.executeQuery();
            table_count.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            String str = "SELECT * \n" +
                         "FROM Evaluation \n" +
                         "WHERE eval_username=? AND jobid IN \n" +
                         "(SELECT id FROM job WHERE submission_date<NOW())";
            pst=conn.prepareStatement(str);
            pst.setString(1, eval_username_5.getText());
            
            rs = pst.executeQuery();
            table_job.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eval_update_grade_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eval_update_grade_BTNActionPerformed
        try{
            String str0 = "SET @user=?";
            pst=conn.prepareStatement(str0);
            pst.setString(1, eval_username_5.getText());
            rs = pst.executeQuery();
            //===============================================
            String str = "UPDATE Evaluation SET Interview_1=?, Report_2=?, 4pragmata_3=? WHERE eval_username=? AND empl_username=? AND jobid=?";
            pst=conn.prepareStatement(str);
            pst.setString(1, grade1.getText());
            pst.setString(2, grade2.getText());
            pst.setString(3, grade3.getText());
            pst.setString(4, eval_username_5.getText());
            pst.setString(5, empl_username.getText());
            pst.setString(6, job_id.getText());
            
            int rowaff = pst.executeUpdate();
            if(rowaff==1)
                grade_affected.setText(rowaff+" rows affected");
            else
                grade_affected.setText("0 rows affected");
            //----------------------------------------------------
            String str1 = "UPDATE evaluationresult SET comments=? WHERE emp_usrname=? AND job_id=?";
            pst=conn.prepareStatement(str1);
            pst.setString(1, grade1_comments.getText());
            pst.setString(2, empl_username.getText());
            pst.setString(3, job_id.getText());
            pst.executeUpdate();
            //----------------------------------------------------
            String str2 =  "CALL check_evaluation(?, ?)";
            pst=conn.prepareStatement(str2);
            
            pst.setString(1, job_id.getText());
            pst.setString(2, eval_username_5.getText());
            pst.executeUpdate();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        /*try{
            String str = "UPDATE Evaluation SET Interview_1=?, Report_2=?, 4pragmata_3=? WHERE eval_username=? AND empl_username=? AND jobid=?" + "UPDATE evaluationresult SET comments=? WHERE emp_usrname=? AND job_id=?" + "CALL check_evaluation(?, ?)";
            pst=conn.prepareStatement(str);
            pst.setString(1, grade1.getText());
            pst.setString(2, grade2.getText());
            pst.setString(3, grade3.getText());
            pst.setString(4, eval_username_5.getText());
            pst.setString(5, empl_username.getText());
            pst.setString(6, job_id.getText());
            pst.setString(7, grade1_comments.getText());
            pst.setString(8, empl_username.getText());
            pst.setString(9, job_id.getText());
            pst.setString(10, job_id.getText());
            pst.setString(11, eval_username_5.getText());
            
            int rowaff = pst.executeUpdate();
            if(rowaff==1)
                grade_affected.setText(rowaff+" rows affected");
            else
                grade_affected.setText("0 rows affexted");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }*/
    }//GEN-LAST:event_eval_update_grade_BTNActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Evaluator_Main_Frame EMF = new Evaluator_Main_Frame();
        Evaluator_Main_Frame.eval_username.setText(eval_username_5.getText());
        EMF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
/*
delete from evaluationresult where Evld=0131;
INSERT INTO evaluationresult(Evld, emp_usrname, job_id, grade, comments) VALUES
(0131, 'Johnny', 7, NULL, NULL);

delete from Evaluation where eval_usename='elsa' and jobid=7;
INSERT INTO Evaluation(eval_username, Interview_1, Report_2, 4pragmata_3, state, empl_username, jobid) VALUES  
('elsa', NULL, NULL, NULL, 'Temporary', 'Johnny', 7);  
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluator_Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluator_Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluator_Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluator_Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluator_Grades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empl_username;
    private javax.swing.JButton eval_update_grade_BTN;
    public static javax.swing.JLabel eval_username_5;
    private javax.swing.JTextField grade1;
    private javax.swing.JTextField grade1_comments;
    private javax.swing.JTextField grade2;
    private javax.swing.JTextField grade3;
    private javax.swing.JLabel grade_affected;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField job_id;
    private javax.swing.JTable table_count;
    private javax.swing.JTable table_job;
    // End of variables declaration//GEN-END:variables
}
