package dbproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Manager_show_update_employee extends javax.swing.JFrame {
    
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    public Manager_show_update_employee() {
        conn=CheckConnection.ConnectDb();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        employee_username = new javax.swing.JLabel();
        Employee_Username = new javax.swing.JTextField();
        back_button = new javax.swing.JButton();
        show_button = new javax.swing.JButton();
        upd_button = new javax.swing.JButton();
        emp_bio = new javax.swing.JLabel();
        emp_sistatikes = new javax.swing.JLabel();
        emp_certificates = new javax.swing.JLabel();
        emp_awards = new javax.swing.JLabel();
        emp_expyears = new javax.swing.JLabel();
        emp_am = new javax.swing.JLabel();
        emp_afmcompany = new javax.swing.JLabel();
        Employee_Bio = new javax.swing.JTextField();
        Employee_Sistatikes = new javax.swing.JTextField();
        Employee_Certificates = new javax.swing.JTextField();
        Employee_Awards = new javax.swing.JTextField();
        Employee_Exp_years = new javax.swing.JTextField();
        Employee_Am = new javax.swing.JTextField();
        Employee_Company_afm = new javax.swing.JTextField();
        manager_username_3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Give the employee's username");

        employee_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_username.setText("Username");

        Employee_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        back_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        show_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        show_button.setText("Show");
        show_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_buttonActionPerformed(evt);
            }
        });

        upd_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        upd_button.setText("Update");
        upd_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_buttonActionPerformed(evt);
            }
        });

        emp_bio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emp_bio.setText("bio");

        emp_sistatikes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emp_sistatikes.setText("sistatikes");

        emp_certificates.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emp_certificates.setText("certificates");

        emp_awards.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emp_awards.setText("awards");

        emp_expyears.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emp_expyears.setText("exp_years");

        emp_am.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emp_am.setText("AM");

        emp_afmcompany.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emp_afmcompany.setText("afm_company");

        Employee_Bio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Employee_Sistatikes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Employee_Certificates.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Employee_Certificates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_CertificatesActionPerformed(evt);
            }
        });

        Employee_Awards.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Employee_Exp_years.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Employee_Am.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Employee_Company_afm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Employee_Company_afm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_Company_afmActionPerformed(evt);
            }
        });

        manager_username_3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manager_username_3.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employee_username)
                        .addGap(95, 95, 95)
                        .addComponent(Employee_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_bio)
                            .addComponent(emp_sistatikes)
                            .addComponent(emp_certificates)
                            .addComponent(emp_awards)
                            .addComponent(emp_expyears)
                            .addComponent(emp_am)
                            .addComponent(emp_afmcompany))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Employee_Sistatikes)
                            .addComponent(Employee_Certificates)
                            .addComponent(Employee_Awards)
                            .addComponent(Employee_Exp_years)
                            .addComponent(Employee_Am)
                            .addComponent(Employee_Company_afm, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(Employee_Bio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(manager_username_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(show_button)
                        .addGap(112, 112, 112)
                        .addComponent(upd_button)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manager_username_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee_username)
                    .addComponent(Employee_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_bio)
                    .addComponent(Employee_Bio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_sistatikes)
                    .addComponent(Employee_Sistatikes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_certificates)
                    .addComponent(Employee_Certificates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_awards)
                    .addComponent(Employee_Awards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_expyears)
                    .addComponent(Employee_Exp_years, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_am)
                    .addComponent(Employee_Am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_afmcompany)
                    .addComponent(Employee_Company_afm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_button)
                    .addComponent(show_button)
                    .addComponent(upd_button))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        Manager_Main_Frame MMF = new Manager_Main_Frame();
        Manager_Main_Frame.manager_username_1.setText(manager_username_3.getText());
        MMF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void show_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_buttonActionPerformed
        // TODO add your handling code here:
        String empluser=Employee_Username.getText();
     
        try{
            String sql_query="SELECT * FROM employee WHERE username=?";
            pst=conn.prepareStatement(sql_query);
            
            pst.setString(1, empluser);
            
            rs=pst.executeQuery();
            while(rs.next()){
                Employee_Bio.setText(rs.getString("bio"));
                Employee_Sistatikes.setText(rs.getString("sistatikes"));
                Employee_Certificates.setText(rs.getString("certificates"));
                Employee_Awards.setText(rs.getString("awards"));
                Employee_Exp_years.setText(rs.getString("exp_years"));
                Employee_Am.setText(rs.getString("AM"));
                Employee_Company_afm.setText(rs.getString("afm_company"));
            }
       
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
             }
    }//GEN-LAST:event_show_buttonActionPerformed

    private void Employee_CertificatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_CertificatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_CertificatesActionPerformed

    private void Employee_Company_afmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_Company_afmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_Company_afmActionPerformed

    private void upd_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_buttonActionPerformed
        // TODO add your handling code here:
        String newsistatikes=Employee_Sistatikes.getText();
        String newcertificates=Employee_Certificates.getText();
        String newawards=Employee_Awards.getText();
        String empluser=Employee_Username.getText();
     
        try{
            String str1 = "SET @user=?";
            pst=conn.prepareStatement(str1);
            pst.setString(1, manager_username_3.getText());
            rs = pst.executeQuery();
            //===================================================
            String sql_query="UPDATE employee SET sistatikes = ?, certificates = ?, awards = ? WHERE username = ?";
            pst=conn.prepareStatement(sql_query);
            
            pst.setString(1, newsistatikes);
            pst.setString(2, newcertificates);
            pst.setString(3, newawards);
            pst.setString(4, empluser);
            
            int rowaff = pst.executeUpdate();
            //rs=pst.executeQuery();
            
            JOptionPane.showMessageDialog(null, "Data succesfully updated!");
            
            Manager_Main_Frame MMF = new Manager_Main_Frame();
            Manager_Main_Frame.manager_username_1.setText(manager_username_3.getText());
            MMF.setVisible(true);
            this.dispose();
            
             }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
             }
    }//GEN-LAST:event_upd_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_show_update_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_show_update_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_show_update_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_show_update_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_show_update_employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Employee_Am;
    private javax.swing.JTextField Employee_Awards;
    private javax.swing.JTextField Employee_Bio;
    private javax.swing.JTextField Employee_Certificates;
    private javax.swing.JTextField Employee_Company_afm;
    private javax.swing.JTextField Employee_Exp_years;
    private javax.swing.JTextField Employee_Sistatikes;
    private javax.swing.JTextField Employee_Username;
    private javax.swing.JButton back_button;
    private javax.swing.JLabel emp_afmcompany;
    private javax.swing.JLabel emp_am;
    private javax.swing.JLabel emp_awards;
    private javax.swing.JLabel emp_bio;
    private javax.swing.JLabel emp_certificates;
    private javax.swing.JLabel emp_expyears;
    private javax.swing.JLabel emp_sistatikes;
    private javax.swing.JLabel employee_username;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel manager_username_3;
    private javax.swing.JButton show_button;
    private javax.swing.JButton upd_button;
    // End of variables declaration//GEN-END:variables
}
