package dbproject;

public class Manager_Main_Frame extends javax.swing.JFrame {

    public Manager_Main_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question_for_actions = new javax.swing.JLabel();
        change_data_company = new javax.swing.JButton();
        change_password_email = new javax.swing.JButton();
        modify_salary = new javax.swing.JButton();
        show_results_of_final_evaluations = new javax.swing.JButton();
        mo_for_evaluators = new javax.swing.JButton();
        upd_employee = new javax.swing.JButton();
        requests_results_evaluator = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        manager_username_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question_for_actions.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        question_for_actions.setForeground(new java.awt.Color(0, 102, 102));
        question_for_actions.setText("What action would you like to do?");

        change_data_company.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        change_data_company.setText("Change the data of your company");
        change_data_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_data_companyActionPerformed(evt);
            }
        });

        change_password_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        change_password_email.setText("Change password and e-mail");
        change_password_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_password_emailActionPerformed(evt);
            }
        });

        modify_salary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modify_salary.setText("Modify salary for a job in your company");
        modify_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_salaryActionPerformed(evt);
            }
        });

        show_results_of_final_evaluations.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        show_results_of_final_evaluations.setText("Show the evaluations results for the jobs in your company, where the evaluation is final");
        show_results_of_final_evaluations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_results_of_final_evaluationsActionPerformed(evt);
            }
        });

        mo_for_evaluators.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mo_for_evaluators.setText("Show M.O of evaluation grades for all evaluators");
        mo_for_evaluators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mo_for_evaluatorsActionPerformed(evt);
            }
        });

        upd_employee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        upd_employee.setText("Show and update the folder of an employee(sistatikes,certificates,awards)");
        upd_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_employeeActionPerformed(evt);
            }
        });

        requests_results_evaluator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        requests_results_evaluator.setText("Show requests,final evaluations results and name,surname of the evaluator for a given employee  ");
        requests_results_evaluator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requests_results_evaluatorActionPerformed(evt);
            }
        });

        logout_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout_button.setText("Log Out");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        manager_username_1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manager_username_1.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(upd_employee, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                            .addComponent(mo_for_evaluators, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                            .addComponent(show_results_of_final_evaluations, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                            .addComponent(modify_salary, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                            .addComponent(change_password_email, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                            .addComponent(change_data_company, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                            .addComponent(requests_results_evaluator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logout_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(question_for_actions)
                        .addGap(51, 51, 51)
                        .addComponent(manager_username_1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(question_for_actions, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(manager_username_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(change_data_company)
                .addGap(18, 18, 18)
                .addComponent(change_password_email)
                .addGap(18, 18, 18)
                .addComponent(modify_salary)
                .addGap(18, 18, 18)
                .addComponent(show_results_of_final_evaluations)
                .addGap(18, 18, 18)
                .addComponent(mo_for_evaluators)
                .addGap(18, 18, 18)
                .addComponent(upd_employee)
                .addGap(18, 18, 18)
                .addComponent(requests_results_evaluator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(logout_button)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void change_data_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_data_companyActionPerformed
        // if button clicked
        this.dispose();
        new Manager_change_data().setVisible(true);
    }//GEN-LAST:event_change_data_companyActionPerformed

    private void change_password_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_password_emailActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Manager_change_mail_password().setVisible(true);
    }//GEN-LAST:event_change_password_emailActionPerformed

    private void modify_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_salaryActionPerformed
        // TODO add your handling code here:
        Manager_modify_salary MMS = new Manager_modify_salary();
        Manager_modify_salary.manager_username_2.setText(manager_username_1.getText());
        MMS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modify_salaryActionPerformed

    private void upd_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_employeeActionPerformed
        // TODO add your handling code here:
        Manager_show_update_employee MSUE = new Manager_show_update_employee();
        Manager_show_update_employee.manager_username_3.setText(manager_username_1.getText());
        MSUE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_upd_employeeActionPerformed

    private void show_results_of_final_evaluationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_results_of_final_evaluationsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Manager_show_final_evalresults().setVisible(true);
    }//GEN-LAST:event_show_results_of_final_evaluationsActionPerformed

    private void requests_results_evaluatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requests_results_evaluatorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Manager_requests_evaluations().setVisible(true);
    }//GEN-LAST:event_requests_results_evaluatorActionPerformed

    private void mo_for_evaluatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mo_for_evaluatorsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Manager_MO_evaluations().setVisible(true);
    }//GEN-LAST:event_mo_for_evaluatorsActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logout_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_data_company;
    private javax.swing.JButton change_password_email;
    private javax.swing.JButton logout_button;
    public static javax.swing.JLabel manager_username_1;
    private javax.swing.JButton mo_for_evaluators;
    private javax.swing.JButton modify_salary;
    private javax.swing.JLabel question_for_actions;
    private javax.swing.JButton requests_results_evaluator;
    private javax.swing.JButton show_results_of_final_evaluations;
    private javax.swing.JButton upd_employee;
    // End of variables declaration//GEN-END:variables
}
