package dbproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Manager_change_data extends javax.swing.JFrame {
    
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    public Manager_change_data() {
        conn=CheckConnection.ConnectDb();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        company_afm = new javax.swing.JLabel();
        company_doy = new javax.swing.JLabel();
        company_name = new javax.swing.JLabel();
        company_phone = new javax.swing.JLabel();
        company_street = new javax.swing.JLabel();
        company_num = new javax.swing.JLabel();
        company_city = new javax.swing.JLabel();
        company_country = new javax.swing.JLabel();
        Afm = new javax.swing.JTextField();
        Doy = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Number = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        Country = new javax.swing.JTextField();
        back_button = new javax.swing.JButton();
        change_button = new javax.swing.JButton();
        Street = new javax.swing.JTextField();
        company_current_afm = new javax.swing.JLabel();
        Current_afm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Change your company data");

        company_afm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_afm.setText("AFM");

        company_doy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_doy.setText("DOY");

        company_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_name.setText("Name");

        company_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_phone.setText("phone");

        company_street.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_street.setText("street");

        company_num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_num.setText("num");

        company_city.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_city.setText("city");

        company_country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_country.setText("country");

        Afm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Doy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Number.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        City.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        back_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        change_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        change_button.setText("Change");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        Street.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        company_current_afm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_current_afm.setText("Current AFM");

        Current_afm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(company_num)
                    .addComponent(company_city)
                    .addComponent(company_phone)
                    .addComponent(company_street)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(company_name)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(company_doy)
                                    .addComponent(company_afm))
                                .addComponent(company_current_afm)
                                .addComponent(company_country))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Afm)
                                    .addComponent(Doy)
                                    .addComponent(Phone)
                                    .addComponent(City)
                                    .addComponent(Number)
                                    .addComponent(Street)
                                    .addComponent(Current_afm, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(change_button)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Afm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(company_afm))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company_doy)
                    .addComponent(Doy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company_name)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company_phone)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company_street)
                    .addComponent(Street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(company_num))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company_city)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company_country)
                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(company_current_afm)
                    .addComponent(Current_afm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(change_button)
                    .addComponent(back_button))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        // TODO add your handling code here:
        String afm=Afm.getText();
        String doy=Doy.getText();
        String name=Name.getText();
        String phone=Phone.getText();
        String num=Number.getText();
        String street=Street.getText();
        String city=City.getText();
        String country=Country.getText();
        String current_AFM=Current_afm.getText();
        
        try{
            String sql_query="UPDATE company SET AFM =?, DOY = ?, Name = ?, phone = ?, street = ?, num = ?, city = ?, country = ? WHERE AFM = ?";
            pst=conn.prepareStatement(sql_query);
            
            pst.setString(1, afm);
            pst.setString(2, doy);
            pst.setString(3, name);
            pst.setString(4, phone);
            pst.setString(5, street);
            pst.setString(6, num);
            pst.setString(7, city);
            pst.setString(8, country);
            pst.setString(9, current_AFM);
            
            rs=pst.executeQuery();
            
            JOptionPane.showMessageDialog(null, "Data succesfully changed!");
            
            this.dispose();
                    new Manager_Main_Frame().setVisible(true);
            
             }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
             }
    }//GEN-LAST:event_change_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Manager_Main_Frame().setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_change_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_change_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_change_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_change_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_change_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Afm;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Country;
    private javax.swing.JTextField Current_afm;
    private javax.swing.JTextField Doy;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Number;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Street;
    private javax.swing.JButton back_button;
    private javax.swing.JButton change_button;
    private javax.swing.JLabel company_afm;
    private javax.swing.JLabel company_city;
    private javax.swing.JLabel company_country;
    private javax.swing.JLabel company_current_afm;
    private javax.swing.JLabel company_doy;
    private javax.swing.JLabel company_name;
    private javax.swing.JLabel company_num;
    private javax.swing.JLabel company_phone;
    private javax.swing.JLabel company_street;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
